project_id = "lgrugpsyewvinlkgmeve"

[functions.create-checkout-session]
verify_jwt = false

[functions.generate-demo-audio]
verify_jwt = false

[functions.send-influencer-term]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.suggest-blog-title]
verify_jwt = false